import { DesignStyleOption } from "@/types";

export const DESIGN_STYLES: DesignStyleOption[] = [
  {
    id: "japandi",
    name: "Japandi",
    description: "Harmonious blend of Japanese minimalism and warm Scandinavian functionality.",
    promptKeyword: "Japandi interior style, warm organic wood slats, tatami textures, neutral earthy palette, minimalist low-profile furniture, tranquil zen aesthetic, soft diffused lighting",
    imageUrl: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=600&q=80",
    tag: "Minimal & Serene",
  },
  {
    id: "modern_minimalist",
    name: "Modern Minimalist",
    description: "Sleek lines, uncluttered architecture, hidden storage, and monolithic surfaces.",
    promptKeyword: "Ultra modern minimalist interior, clean sharp lines, concealed architectural lighting, microcement floors, matte black accents, spacious airy atmosphere",
    imageUrl: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=600&q=80",
    tag: "Clean & Sleek",
  },
  {
    id: "mid_century_modern",
    name: "Mid-Century Modern",
    description: "1950s iconic curves, warm teak woodwork, tapered legs, and organic geometric forms.",
    promptKeyword: "Mid-century modern interior, authentic walnut wood paneling, Eames lounge aesthetic, mustard and olive accents, large picture windows, brass pendant lamps",
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=80",
    tag: "Timeless Classic",
  },
  {
    id: "scandinavian",
    name: "Scandinavian Hygge",
    description: "Cozy hygge textures, pale birch, crisp white walls, and warm ambient glowing lamps.",
    promptKeyword: "Scandinavian interior design, pale oak flooring, cozy woolen throws, bouclé armchairs, soft morning sunlight, serene Nordic elegance",
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=600&q=80",
    tag: "Warm & Cozy",
  },
  {
    id: "industrial_loft",
    name: "Industrial Loft",
    description: "Raw exposed brickwork, steel beams, weathered cognac leather, and Edison bulbs.",
    promptKeyword: "Tribeca industrial loft interior, double height ceiling, exposed red brick walls, black iron mullioned windows, distressed leather sofa, polished concrete",
    imageUrl: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=600&q=80",
    tag: "Urban & Raw",
  },
  {
    id: "wabi_sabi",
    name: "Wabi-Sabi Organic",
    description: "Beauty in natural imperfection, raw lime plaster, handcrafted ceramics, and weathered stone.",
    promptKeyword: "Wabi-sabi organic interior, rough textured clay walls, unvarnished aged timber, linen upholstery, organic ceramic vessels, tranquil meditative shadow play",
    imageUrl: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=600&q=80",
    tag: "Natural & Earthy",
  },
  {
    id: "contemporary_luxury",
    name: "Contemporary Luxury",
    description: "Polished Calacatta marble, brushed champagne gold trims, and bespoke Italian furnishings.",
    promptKeyword: "Ultra high-end contemporary luxury penthouse, bookmatched Calacatta marble, brushed champagne bronze trims, custom velvet sectional, crystal chandelier",
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=600&q=80",
    tag: "Opulent & Luxe",
  },
  {
    id: "bohemian_chic",
    name: "Bohemian Chic",
    description: "Eclectic macrame, Moroccan rugs, lush monstera plants, and warm terracotta tones.",
    promptKeyword: "Boho chic interior design, layered vintage Persian rugs, woven rattan pendants, cascading fiddle leaf figs, terracotta pottery, warm vibrant sunlight",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80",
    tag: "Eclectic & Free",
  },
  {
    id: "coastal_breeze",
    name: "Coastal Hamptons",
    description: "Crisp navy and linen whites, shiplap detailing, bleached oak, and airy seaside lighting.",
    promptKeyword: "Hamptons coastal luxury interior, crisp white shiplap walls, nautical navy accents, bleached driftwood dining table, large sunlit terrace doors",
    imageUrl: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=600&q=80",
    tag: "Airy & Coastal",
  },
  {
    id: "biophilic_greenery",
    name: "Biophilic Oasis",
    description: "Living green moss walls, abundant indoor botanicals, natural slate, and skylight illumination.",
    promptKeyword: "Biophilic interior architecture, indoor vertical plant wall, large glass atrium skylight, natural riverstone accents, solid bamboo elements, rainforest freshness",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80",
    tag: "Green & Healthy",
  },
  {
    id: "cyberpunk_neon",
    name: "Cyberpunk & Neon Noir",
    description: "Futuristic dark mode ambiance, neon cyan & magenta mood lighting, and high-tech fixtures.",
    promptKeyword: "Cyberpunk futuristic interior aesthetic, dark reflective glass, matte black titanium surfaces, concealed RGB neon ambient glow (cyan and magenta), sleek holographic detailing",
    imageUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=600&q=80",
    tag: "Futuristic & Glow",
  },
  {
    id: "art_deco",
    name: "Art Deco Glamour",
    description: "Gilded geometric brass screens, rich emerald velvets, chevron marble, and 1920s Gatsby charm.",
    promptKeyword: "1920s Art Deco luxury interior, geometric brass sunburst motifs, deep emerald green velvet chairs, black and gold marble checkerboard floor, crystal globe sconces",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80",
    tag: "Glamour & Vintage",
  },
  {
    id: "mediterranean_villa",
    name: "Mediterranean Villa",
    description: "Sun-drenched stucco, terracotta roof tiles, arched doorways, and olive branch urns.",
    promptKeyword: "Mediterranean coastal villa interior, whitewashed lime plaster arches, terracotta tile flooring, hand-painted ceramic tiles, breezy linen curtains, olive tree in stone planter",
    imageUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=600&q=80",
    tag: "Sun-Drenched",
  },
  {
    id: "farmhouse_chic",
    name: "Modern Farmhouse",
    description: "Reclaimed barnwood beams, apron-front sinks, black iron hardware, and neutral shaker cabinets.",
    promptKeyword: "Modern farmhouse interior, cathedral ceiling with reclaimed timber beams, white shaker kitchen cabinetry, black iron hardware, cozy stone fireplace",
    imageUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=600&q=80",
    tag: "Rustic & Warm",
  },
  {
    id: "japanese_zen",
    name: "Japanese Zen Minimal",
    description: "Shoji screens, low-lying tea tables, hinoki cypress aroma, and peaceful moss gardens.",
    promptKeyword: "Authentic Japanese Zen interior, shoji paper sliding screens, low cedar wood chabudai table, bonsai tree display, natural reed tatami mats, calm minimalist balance",
    imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=600&q=80",
    tag: "Zen & Meditative",
  },
  {
    id: "desert_modern",
    name: "Desert Modern (Palm Springs)",
    description: "Earthy ochre tones, saguaro cactus planters, cantilevered rooflines, and sandstone walls.",
    promptKeyword: "Palm Springs desert modern interior, rammed earth feature wall, mid-century geometry, canyon sunset color palette, terrazzo floors, expansive glass sliding walls",
    imageUrl: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=600&q=80",
    tag: "Warm Desert",
  },
  {
    id: "bauhaus",
    name: "Bauhaus Functionalism",
    description: "Form follows function, tubular chrome chairs, primary color accents, and crisp glass architecture.",
    promptKeyword: "Bauhaus modernist interior, tubular chrome Cantilever chairs, primary Bauhaus color accents (blue, red, yellow), functional steel and glass structure, timeless rational design",
    imageUrl: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=600&q=80",
    tag: "Architectural",
  },
  {
    id: "neo_classical",
    name: "Neo-Classical Parisian",
    description: "Intricate boiserie wall paneling, herringbone parquet flooring, marble fireplaces, and high moldings.",
    promptKeyword: "Haussmannian Parisian apartment interior, intricate white boiserie molding, oak herringbone parquet floor, antique gilded mirror above marble mantle, modern minimalist chandelier",
    imageUrl: "https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=600&q=80",
    tag: "Parisian Elegance",
  },
  {
    id: "rustic_mountain",
    name: "Rustic Mountain Lodge",
    description: "River rock fireplaces, heavy timber trusses, faux fur throws, and panoramic alpine views.",
    promptKeyword: "Aspen mountain lodge interior, massive natural stone fireplace, heavy dark timber log beams, cozy shearling armchairs, floor-to-ceiling windows overlooking snowcapped pines",
    imageUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80",
    tag: "Lodge & Alpine",
  },
  {
    id: "futuristic_minimal",
    name: "Futuristic Monolith",
    description: "Curved aerodynamic architectural geometry, seamless monolithic surfaces, and invisible acoustics.",
    promptKeyword: "Futuristic parametric interior design, flowing organic curved walls, seamless white solid surface, integrated indirect floor cove lighting, sci-fi minimalist architecture",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80",
    tag: "Next-Gen",
  },
];
