import { PricingPlan } from "@/types";

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter Interior",
    priceUSD: 19,
    priceINR: 1499,
    credits: 50,
    description: "Ideal for homeowners, DIY decorators, and individual room remodeling.",
    features: [
      "50 AI Room Redesigns / month",
      "Standard SDXL Lightning Generation (3s)",
      "Access to all 15 Room Types",
      "Access to all 20+ Design Styles",
      "Interactive Before/After Wipe Slider",
      "Standard Resolution Exports (1080p)",
      "Basic AI Cost Estimation",
    ],
    popular: false,
    stripePriceId: process.env.STRIPE_STARTER_PRICE_ID || "price_starter",
  },
  {
    id: "pro",
    name: "Professional Designer",
    priceUSD: 49,
    priceINR: 3999,
    credits: 200,
    description: "Built for interior designers, architects, real estate agents, and stagers.",
    features: [
      "200 AI Room Redesigns / month",
      "Ultra-Fast Dedicated GPU Pipeline",
      "Full 4K Ultra-HD Upscaling",
      "Advanced Depth ControlNet Precision",
      "Custom Materials & Color Palettes",
      "Export Itemized PDF Cost Budget Reports",
      "Commercial Client Usage License",
      "Priority Customer Support",
    ],
    popular: true,
    stripePriceId: process.env.STRIPE_PRO_PRICE_ID || "price_pro",
  },
  {
    id: "enterprise",
    name: "Enterprise Studio",
    priceUSD: 149,
    priceINR: 11999,
    credits: 1000,
    description: "Uncapped horsepower for large design studios, staging agencies & developers.",
    features: [
      "1,000 AI Redesigns / month",
      "Custom Fine-Tuned Furniture Catalogs",
      "Team Collaboration & Project Workspaces",
      "White-Label Branded PDF Budget Exports",
      "Direct API Access & Webhook Feeds",
      "Batch Image Multi-Angle Processing",
      "Dedicated Solutions Architect",
      "99.9% SLA & 24/7 VIP Phone Support",
    ],
    popular: false,
    stripePriceId: process.env.STRIPE_ENTERPRISE_PRICE_ID || "price_enterprise",
  },
];
